name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate static sites
        run: npm run generate

      - name: Build
        run: npm run build

      - name: Upload generated static sites
        uses: actions/upload-artifact@v4
        with:
          name: generated-sites
          path: output
          if-no-files-found: error

      - name: Upload Next.js build
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
          if-no-files-found: error
